apiVersion: v1
kind: ConfigMap
metadata:
  name: brechtel-msems9404-112-config
  namespace: envds
  labels:
    app: brechtel-msems9404-112
data:
  sensor.conf: |
    serial_number: "112"
    daq_id: clearsky
    interfaces:
      # default: serial
      default:
        interface_env_id: clear # if omitted, defaults to envds_id of sensor
        interface_id: NetBurner::SB70LC::nb54
        # interface_id: NetBurner::SB70LC::home38
        # path: port, channel, etc
        path: port-2
      #   connection-properties:
      #     baudrate: 115200
      #     bytesize: 8
      #     parity: N
      #     stopbit: 1
      #   # read-properties:
      #     read_method: "readline" # default
      #     # terminator: "\r"
      #     # binary: true
      #     # num-bytes: 1
      #     # decode-errors: strict
      # # power: # example of second interface (e.g., CDP enable signal)
      # #   interface_id: system::mock::localhost
      # #   path: port-01
      
    # settings: # used to override defaults
      sheath_sp: 2.0
      scan_max_dia: 420
      scan_min_dia: 10
      num_bins: 30
      bin_time: 1
      mcpcpwr: 0
      msems_mode: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brechtel-msems9404-112
  namespace: envds
  labels:
    app: brechtel-msems9404-112
spec:
  selector:
    matchLabels:
      app: brechtel-msems9404-112
  template:
    metadata:
      labels:
        app: brechtel-msems9404-112
        app-group: envds-sensor-clear
    spec:
      containers:
      - name: brechtel-msems9404-112
        image: envds-registry-clear:5000/envds/sensor/brechtel-msems9404:0.1.0
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_ENV_ID
            value: clear
          - name: REDIS_OM_URL
            value: redis://redis.default
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: brechtel-msems9404-112-config
              mountPath: /app/config/sensor.conf
              subPath: sensor.conf
            # - name: mosquitto-certs
            #   mountPath: /certs/ca.crt
            #   subPath: ca.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.crt
            #   subPath: server.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.key
            #   subPath: server.key
      volumes:
        - name: brechtel-msems9404-112-config
          configMap:
            name: brechtel-msems9404-112-config
        # - name: mosquitto-certs
        #   configMap:
        #     name: mosquitto-certs
---
apiVersion: v1
kind: Service
metadata:
  name: brechtel-msems9404-112
  namespace: envds
  labels:
    app: brechtel-msems9404-112
spec:
  selector:
    app: brechtel-msems9404-112
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
  # - name: https
  #   port: 8883
  #   targetPort: 8883
  # type: LoadBalancer
  type: ClusterIP
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: brechtel-msems9404-112-stripprefix
#   namespace: envds
#   labels:
#     app: envds
# spec:
#   stripPrefix:
#     prefixes:
#       - /envds/sensor/MockCo/Mock1/1234
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: brechtel-msems9404-112-ingress
#   namespace: envds
#   # labels:
#   #   app: envds
#   annotations:
#     ingress.kubernetes.io/ssl-redirect: "false"
#     traefik.ingress.kubernetes.io/router.middlewares:
#       envds-brechtel-msems9404-112-stripprefix@kubernetescrd
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /envds/sensor/AerosolDynamics/MAGIC250/143
#         pathType: Prefix
#         backend:
#           service:
#             name: brechtel-msems9404-112
#             port:
#               number: 9080
