# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: envds-dataserver-dev-pv-volume
#   namespace: envds
#   labels:
#     type: local
# spec:
#   storageClassName: local-path
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/data/envds/data"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: envds-files-dev-pv-claim
#   namespace: envds
# spec:
#   storageClassName: local-path
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envds-dataserver-dev
  namespace: envds
  labels:
    app: envds-dataserver-dev
spec:
  selector:
    matchLabels:
      app: envds-dataserver-dev
  template:
    metadata:
      labels:
        app: envds-dataserver-dev
    spec:
      containers:
      - name: envds-dataserver-dev
        image: envds-registry:5000/envds/envds-dataserver:0.1.0
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_ENV_ID
            value: main
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
      #   volumeMounts:
      #     - name: envds-dataserver-dev-pv-storage
      #       mountPath: /data
      # volumes:
      #   - name: envds-dataserver-dev-pv-storage
      #     persistentVolumeClaim:
      #       claimName: envds-dataserver-dev-pv-claim
         # - name: https
        #   containerPort: 8883
        #   protocol: TCP
      #   volumeMounts:
      #       - name: mosquitto-config
      #         mountPath: /mosquitto/config/mosquitto.conf
      #         subPath: mosquitto.conf
      #       # - name: mosquitto-certs
      #       #   mountPath: /certs/ca.crt
      #       #   subPath: ca.crt
      #       # - name: mosquitto-certs
      #       #   mountPath: /certs/server.crt
      #       #   subPath: server.crt
      #       # - name: mosquitto-certs
      #       #   mountPath: /certs/server.key
      #       #   subPath: server.key
      # volumes:
      #   - name: mosquitto-config
      #     configMap:
      #       name: mosquitto-config
      #   # - name: mosquitto-certs
      #   #   configMap:
      #   #     name: mosquitto-certs
---
apiVersion: v1
kind: Service
metadata:
  name: envds-dataserver-dev
  namespace: envds
  labels:
    app: envds-dataserver-dev
spec:
  selector:
    app: envds-dataserver-dev
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
  # - name: https
  #   port: 8883
  #   targetPort: 8883
  # type: LoadBalancer
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: envds-dataserver-stripprefix
  namespace: envds
  # labels:
  #   app: envds
spec:
  stripPrefix:
    prefixes:
      - /envds/dataserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: envds-dataserver-ingress
  namespace: envds
  # labels:
  #   app: envds
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    traefik.ingress.kubernetes.io/router.middlewares:
      envds-envds-dataserver-stripprefix@kubernetescrd
      # default-erddap-rewrite@kubernetescrd
spec:
  rules:
  - http:
      paths:
      # - path: /erddap
      - path: /envds/dataserver
        pathType: Prefix
        # pathType: Exact
        backend:
          service:
            name: envds-dataserver-dev
            port:
              number: 8080
