apiVersion: v1
kind: ConfigMap
metadata:
  name: mockco-mock1-1235-config
  namespace: envds
  labels:
    app: mockco-mock1-1235
data:
  sensor.conf: |
    serial_number: "1235"
    daq_id: cloudysky
    interfaces:
      # default: serial
      default:
        interface_env_id: dev # if omitted, defaults to envds_id of sensor
        interface_id: system::mock::uas1
        # path: port, channel, etc
        path: port-01
        connection-properties:
          baudrate: 9600
          bytesize: 8
          parity: N
          stopbit: 1
        # read-properties:
          # terminator: "\r"
          # binary: true
          # num-bytes: 1
          # decode-errors: strict
      # power: # example of second interface (e.g., CDP enable signal)
      #   interface_id: system::mock::localhost
      #   path: port-01

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockco-mock1-1235
  namespace: envds
  labels:
    app: mockco-mock1-1235
spec:
  selector:
    matchLabels:
      app: mockco-mock1-1235
  template:
    metadata:
      labels:
        app: mockco-mock1-1235
    spec:
      containers:
      - name: mockco-mock1-1235
        image: envds-registry:5000/envds/sensor/mockco-mock1:0.1.0
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_ENV_ID
            value: dev
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: mockco-mock1-1235-config
              mountPath: /app/config/sensor.conf
              subPath: sensor.conf
            # - name: mosquitto-certs
            #   mountPath: /certs/ca.crt
            #   subPath: ca.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.crt
            #   subPath: server.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.key
            #   subPath: server.key
      volumes:
        - name: mockco-mock1-1235-config
          configMap:
            name: mockco-mock1-1235-config
        # - name: mosquitto-certs
        #   configMap:
        #     name: mosquitto-certs
---
apiVersion: v1
kind: Service
metadata:
  name: mockco-mock1-1235
  namespace: envds
  labels:
    app: mockco-mock1-1235
spec:
  selector:
    app: mockco-mock1-1235
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
  # - name: https
  #   port: 8883
  #   targetPort: 8883
  # type: LoadBalancer
  type: ClusterIP
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: mockco-mock1-1235-stripprefix
#   namespace: envds
#   labels:
#     app: envds
# spec:
#   stripPrefix:
#     prefixes:
#       - /envds/sensor/MockCo/Mock1/1235
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: mockco-mock1-1235-ingress
#   namespace: envds
#   # labels:
#   #   app: envds
#   annotations:
#     ingress.kubernetes.io/ssl-redirect: "false"
#     traefik.ingress.kubernetes.io/router.middlewares:
#       envds-mockco-mock1-1235-stripprefix@kubernetescrd
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /envds/sensor/MockCo/Mock1/1235
#         pathType: Prefix
#         backend:
#           service:
#             name: mockco-mock1-1235
#             port:
#               number: 9080
