apiVersion: v1
kind: PersistentVolume
metadata:
  name: dataserver-data-pv-volume-main
  namespace: envds
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/envds/erddap"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataserver-data-pv-claim-main
  namespace: envds
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
