version: "3.9"
configs:
  mosquitto-conf: |
    sys_interval 1
    autosave_interval 1
    allow_anonymous true
    autosave_on_changes true
    # logs
    log_dest stdout
    log_type all
    log_timestamp true
    log_timestamp_format %Y-%m-%d_%H:%M:%S
    connection_messages true
    # data
    persistence true
    persistence_location /mosquitto/data/
    persistence_file mosquitto.db

    # Non-TLS
    listener 1883
    protocol mqtt

    # TLS
    # https://mosquitto.org/man/mosquitto-tls-7.html
    # listener 8883
    # protocol mqtt
    # cafile /certs/ca.crt
    # certfile /certs/server.crt
    # keyfile /certs/server.key
    # require_certificate false

# services:
#   mosquitto2:
#     image: eclipse-mosquitto:2.0.14
#     ports:
#       - "1884:1883"
#     configs:
#       - source: mosquitto-conf
#         target: /mosquitto/config/mosquitto.conf
