---
apiVersion: envds.dev/v1
kind: ConfigMap
metadata:
  name: envds-config
data:
  envds.conf: |
    sys_interval 1
    autosave_interval 1
    allow_anonymous true
    autosave_on_changes true
    # logs
    log_dest stdout
    log_type all
    log_timestamp true
    log_timestamp_format %Y-%m-%d_%H:%M:%S
---
apiVersion: envds.dev/v1
kind: DataSystem
metadata:
  name: datasystem
  namespace: default
spec:
  containers:
  - name: envds
    image: envds-datasystem:latest
    # resources:
    #   requests:
    #     cpu: "50m"
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    ports:
    - name: api
      containerPort: 9080
      protocol: TCP
    - name: console
      containerPort: 9883
      protocol: TCP
  mqttBroker:
    name: default
    namespace: default
    bridge-to:
      host: 10.55.169.222
      port: 1883
---
apiVersion: envds.dev/v1
kind: DataSystemService
metadata:
  name: 
spec:
  selector:
    app: datasystem
  ports:
  - name: http
    port: 9080
    targetPort: 9080
  - name: https
    port: 9883
    targetPort: 9883