apiVersion: v1
kind: ConfigMap
metadata:
  name: system-mock-localhost-config
  namespace: envds
  labels:
    app: system-mock-localhost
data:
  interface.conf: |
    uid: localhost
    # serial_number: "1234"
    # daq_id: cloudysky
    paths:
      - port-01:
          filepath: /dev/mock/iface02
      # - port-02:
      #     address: 
      #       host: 10.55.169.54
      #       port: 21
      # - port-03:
      #     uri: /dev/mock/iface01

    # interfaces:
    #   # default: serial
    #   serial:
    #     interface_id: mock-interface-01
    #     # path: port, channel, etc
    #     path: "02"
    #     connection-properties:
    #       baudrate: 9600
    #       bytesize: 8
    #       parity: N
    #       stopbit: 1
    #     # read-properties:
    #       # terminator: "\r"
    #       # binary: true
    #       # num-bytes: 1
    #       # decode-errors: strict

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-mock-localhost
  namespace: envds
  labels:
    app: system-mock-localhost
spec:
  selector:
    matchLabels:
      app: system-mock-localhost
  template:
    metadata:
      labels:
        app: system-mock-localhost
    spec:
      containers:
      - name: system-mock-localhost
        image: envds-registry:5000/envds/interface/system-mock:0.1.0
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_ENV_ID
            value: dev
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: system-mock-localhost-config
              mountPath: /app/config/interface.conf
              subPath: interface.conf
            # - name: mosquitto-certs
            #   mountPath: /certs/ca.crt
            #   subPath: ca.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.crt
            #   subPath: server.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.key
            #   subPath: server.key
      volumes:
        - name: system-mock-localhost-config
          configMap:
            name: system-mock-localhost-config
        # - name: mosquitto-certs
        #   configMap:
        #     name: mosquitto-certs
---
apiVersion: v1
kind: Service
metadata:
  name: system-mock-localhost
  namespace: envds
  labels:
    app: system-mock-localhost
spec:
  selector:
    app: system-mock-localhost
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
  # - name: https
  #   port: 8883
  #   targetPort: 8883
  # type: LoadBalancer
  type: ClusterIP
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: system-mock-localhost-stripprefix
#   namespace: envds
#   labels:
#     app: envds
# spec:
#   stripPrefix:
#     prefixes:
#       - /envds/interface/system/mock/01
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: system-mock-localhost-ingress
#   namespace: envds
#   # labels:
#   #   app: envds
#   annotations:
#     ingress.kubernetes.io/ssl-redirect: "false"
#     traefik.ingress.kubernetes.io/router.middlewares:
#       envds-system-mock-localhost-stripprefix@kubernetescrd
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /envds/interface/system/mock/01
#         pathType: Prefix
#         backend:
#           service:
#             name: system-mock-localhost
#             port:
#               number: 9080

