apiVersion: v1
kind: ConfigMap
metadata:
  name: sensiron-sht35-clearstap-config
  namespace: envds
  labels:
    app: sensiron-sht35-clearstap
data:
  sensor.conf: |
    serial_number: "clearstap"
    daq_id: clearsky
    interfaces:
      # default: serial
      default:
        interface_env_id: clear # if omitted, defaults to envds_id of sensor
        interface_id: NetBurner::SB70LC::nb52
        # interface_id: NetBurner::SB70LC::home38
        # path: port, channel, etc
        path: port-I2C

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensiron-sht35-clearstap
  namespace: envds
  labels:
    app: sensiron-sht35-clearstap
spec:
  selector:
    matchLabels:
      app: sensiron-sht35-clearstap
  template:
    metadata:
      labels:
        app: sensiron-sht35-clearstap
    spec:
      containers:
      - name: sensiron-sht35-clearstap
        image: envds-registry-clear:5000/envds/sensor/sensiron-sht35:0.1.0
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_ENV_ID
            value: clear
          - name: REDIS_OM_URL
            value: redis://redis.default
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: sensiron-sht35-clearstap-config
              mountPath: /app/config/sensor.conf
              subPath: sensor.conf
            # - name: mosquitto-certs
            #   mountPath: /certs/ca.crt
            #   subPath: ca.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.crt
            #   subPath: server.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.key
            #   subPath: server.key
      volumes:
        - name: sensiron-sht35-clearstap-config
          configMap:
            name: sensiron-sht35-clearstap-config
        # - name: mosquitto-certs
        #   configMap:
        #     name: mosquitto-certs
---
apiVersion: v1
kind: Service
metadata:
  name: sensiron-sht35-clearstap
  namespace: envds
  labels:
    app: sensiron-sht35-clearstap
spec:
  selector:
    app: sensiron-sht35-clearstap
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
  # - name: https
  #   port: 8883
  #   targetPort: 8883
  # type: LoadBalancer
  type: ClusterIP
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: sensiron-sht35-clearstap-stripprefix
#   namespace: envds
#   labels:
#     app: envds
# spec:
#   stripPrefix:
#     prefixes:
#       - /envds/sensor/MockCo/Mock1/1234
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: sensiron-sht35-clearstap-ingress
#   namespace: envds
#   # labels:
#   #   app: envds
#   annotations:
#     ingress.kubernetes.io/ssl-redirect: "false"
#     traefik.ingress.kubernetes.io/router.middlewares:
#       envds-sensiron-sht35-clearstap-stripprefix@kubernetescrd
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /envds/sensor/AerosolDynamics/MAGIC250/143
#         pathType: Prefix
#         backend:
#           service:
#             name: sensiron-sht35-clearstap
#             port:
#               number: 9080
