apiVersion: v1
kind: ConfigMap
metadata:
  name: mcc-mcc128-clear0-config
  namespace: envds
  labels:
    app: mcc-mcc128-clear0
data:
  interface.conf: |
    uid: localhost
    paths:
      # udp-10080:
      #     client-type: udp
      #     # local-host: 172.18.0.2
      #     local-port: 10080
      #     # local0-port: 31870

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcc-mcc128-clear0
  namespace: envds
  labels:
    app: mcc-mcc128-clear0
spec:
  selector:
    matchLabels:
      app: mcc-mcc128-clear0
  template:
    metadata:
      labels:
        app: mcc-mcc128-clear0
    spec:
      containers:
      - name: mcc-mcc128-clear0
        image: envds-registry-clear:5000/envds/interface/mcc-mcc128:0.1.0
        imagePullPolicy: "Always"
        env:
          - name: ENVDS_ENV_ID
            value: clear
          - name: REDIS_OM_URL
            value: redis://redis.default
          - name: LOG_LEVEL
            value: DEBUG
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 9080
          protocol: TCP
        # - name: https
        #   containerPort: 8883
        #   protocol: TCP
        volumeMounts:
            - name: mcc-mcc128-clear0-config
              mountPath: /app/config/interface.conf
              subPath: interface.conf
            # - name: mosquitto-certs
            #   mountPath: /certs/ca.crt
            #   subPath: ca.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.crt
            #   subPath: server.crt
            # - name: mosquitto-certs
            #   mountPath: /certs/server.key
            #   subPath: server.key
      volumes:
        - name: mcc-mcc128-clear0-config
          configMap:
            name: mcc-mcc128-clear0-config
        # - name: mosquitto-certs
        #   configMap:
        #     name: mosquitto-certs
---
apiVersion: v1
kind: Service
metadata:
  name: mcc-mcc128-clear0
  namespace: envds
  labels:
    app: mcc-mcc128-clear0
spec:
  selector:
    app: mcc-mcc128-clear0
  ports:
  - name: http
    protocol: TCP
    port: 9080
    targetPort: 9080
  # - name: https
  #   port: 8883
  #   targetPort: 8883
  # type: LoadBalancer
  type: ClusterIP
# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: Middleware
# metadata:
#   name: mcc-mcc128-clear0-stripprefix
#   namespace: envds
#   labels:
#     app: envds
# spec:
#   stripPrefix:
#     prefixes:
#       - /envds/interface/system/net/01
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: mcc-mcc128-clear0-ingress
#   namespace: envds
#   # labels:
#   #   app: envds
#   annotations:
#     ingress.kubernetes.io/ssl-redirect: "false"
#     traefik.ingress.kubernetes.io/router.middlewares:
#       envds-mcc-mcc128-clear0-stripprefix@kubernetescrd
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /envds/interface/system/net/01
#         pathType: Prefix
#         backend:
#           service:
#             name: mcc-mcc128-clear0
#             port:
#               number: 9080

