name: Docker Image - envds-files

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v4
    - name: Build the Docker image
      uses: actions/checkout@v4
      with:
        file: ./apps/envds-files/Dockerfile
        context: ./apps/envds-files
        push: true
        tags: envds-files:$(date +%s)
      # run: docker build ./apps/envds-files --file Dockerfile --tag envds-files:$(date +%s)
